-- 002_anket_modulu.sql
--
-- ############################################################################
-- # BİZİM MODÜLÜMÜZ. Host'un tablolarını DEĞİL, anket modülünü kurar.        #
-- ############################################################################
-- 001_ilk_sema.sql host şemasının geliştirme REPLİKASIDIR (üretimde zaten vardır,
-- orada çalıştırılmaz). BU dosya ise tam tersidir: Savronik'in çalışan sistemine
-- EKLEDİĞİMİZ anket modülünün şemasıdır ve üretimde de çalıştırılacak olan tek
-- migration budur. Host tarafında karşılığı YOKTUR.
--
-- Kaynak: projenin MariaDB şeması (database/migrations/001..011 sonrası CANLI hali).
-- Kolonlar, NULL/NOT NULL, DEFAULT, UNIQUE, index ve FK davranışları (ON DELETE /
-- ON UPDATE) birebir korunmuştur; yalnızca ADLAR (İngilizce snake_case) ve TİPLER
-- (PostgreSQL karşılıkları) uyarlanmıştır.
--
-- ÇALIŞTIRMA: savronik_migrate rolüyle, savronik_akademi veritabanı üzerinde.
-- Şema: public — host tablolarıyla AYNI şemada durur (staff'a FK kurulabilmesi ve
-- tek search_path ile çalışılabilmesi için). DDL yalnızca migration ile uygulanır;
-- runtime hesabının (savronik_app) DDL yetkisi YOKTUR.
--
-- ÖN KOŞUL: public.staff tablosu mevcut olmalıdır (üretimde host'ta zaten vardır,
-- geliştirmede 001_ilk_sema.sql ile kurulur). Aksi halde staff FK'leri düşer.
--
-- ---------------------------------------------------------------------------
-- KARARLAR (neden böyle)
-- ---------------------------------------------------------------------------
-- 1) PK'ler: bigint GENERATED BY DEFAULT AS IDENTITY.
--    NEDEN: identity, sequence'ı kendisi üretir ve SAHİPLENİR. Host tarafında elle
--    CREATE SEQUENCE + ALTER COLUMN SET DEFAULT nextval + OWNED BY üçlüsüyle
--    bağlanmış sayaçlarda görülen ad/bağ karmaşası (ör. roleright tablosunun
--    sayacı "role_rigth_id_seq" adını taşır) burada tekrarlanmaz. Ayrıca
--    "BY DEFAULT" seçilmiştir (ALWAYS değil): veri taşıma sırasında MariaDB'deki
--    mevcut id'ler açıkça INSERT edilebilsin diye.
--
-- 2) SAKLANAN DEĞER KODLARI TÜRKÇE KALIR. Tablo ve kolon ADLARI İngilizceye
--    çevrilmiştir, ancak satırlarda saklanan kod değerleri DEĞİŞMEZ:
--      survey.status            : 'Aktif' / 'Pasif'
--      survey.access_level      : 'grup' / 'ben' / 'herkes'
--      survey.survey_type       : 'Kullanıcı Bilgi Anketi', 'Eğitim Davranış Anketi' ...
--      survey_assignment.status : 'atandı' / 'devam_ediyor' / 'tamamlandı'
--      question.question_type   : 'coktan_secmeli_tek', 'evet_hayir', 'skala_5' ...
--      lookup_value.category    : 'konu' / 'amac'
--    NEDEN: bu değerler Service katmanında sabit olarak durur (anket_alan_hazirla.py,
--    soru_service.py, anket_sorgulari.py). Onları çevirmek bir UYGULAMA değişikliğidir
--    ve bu turun kapsamı DEĞİLDİR. Buradaki "İngilizce ad + Türkçe değer" karışımı
--    KAZA DEĞİL, bilinçli bir sınır çizgisidir.
--    DİKKAT: 'atandı' ve 'tamamlandı' Türkçe NOKTALI ı ile yazılır ('atandi' DEĞİL).
--
-- 3) MariaDB'de bu 8 tabloda CHECK kısıtı YOKTUR. Tek istisna olarak
--    survey_assignment'a tamamlanma tutarlılığı CHECK'i EKLENMİŞTİR (bkz. tablo
--    yorumu); geri kalan her şey birebirdir.
--
-- 4) PostgreSQL FK kolonlarını OTOMATİK indekslemez (MariaDB/InnoDB indeksler).
--    MariaDB'nin FK'lerle birlikte ürettiği KEY'lerin karşılığı olarak indeksler
--    dosya sonunda AÇIKÇA oluşturulur; aksi halde silme/join performansı kaybolurdu.
--
-- ---------------------------------------------------------------------------
-- KOLON EŞLEME TABLOSU (MariaDB -> PostgreSQL)
-- Repository sorguları çevrilirken REFERANS budur. Ayrı bir doc dosyası tutulmaz;
-- eşleme şemayla aynı dosyada yaşar ki senkronize kalsın.
-- ---------------------------------------------------------------------------
--
-- Anket -> survey
--   anket_id            int PK AI          -> id                     bigint identity PK
--   ad                  varchar(255) NN    -> name                   varchar(255) NN
--   on_yazi             text               -> intro_text             text
--   son_yazi            text               -> closing_text           text
--   aciklama            text               -> description            text
--   durum               varchar(50) NN     -> status                 varchar(50) NN
--   anket_tipi          varchar(50)        -> survey_type            varchar(50)
--   erisim_seviyesi     varchar(50)        -> access_level           varchar(50)
--   erisim_grup_id      int FK             -> access_group_id        bigint  [FK YOK — bkz. BLOKE]
--   baslangic_tarihi    datetime           -> start_at               timestamp   (TARİH+SAAT tutar)
--   bitis_tarihi        datetime           -> end_at                 timestamp   (TARİH+SAAT tutar)
--   almak_zorunda       tinyint(1) NN d0   -> is_mandatory           boolean NN d false
--   ana_sayfada_goster  tinyint(1) NN d0   -> show_on_home_page      boolean NN d false
--   sira_no_goster      tinyint(1) NN d1   -> show_question_numbers  boolean NN d true
--   soru_gosterim_tipi  varchar(50)        -> question_display_type  varchar(50)
--   olusturan_kodu      varchar(20) FK     -> created_by             bigint FK staff  [TİP: varchar->bigint]
--   olusturma_tarihi    datetime NN d now  -> created_at             timestamp NN d LOCALTIMESTAMP
--
-- Soru -> question
--   soru_id             int PK AI          -> id                     bigint identity PK
--   anket_id            int FK             -> TAŞINMADI (ölü kolon; bkz. aşağıdaki gerekçe)
--     GEREKÇE: migration 011 ile anket<->soru bağı AnketSoru (survey_question) ara
--     tablosuna taşındı; bu kolon o tarihten beri ÖLÜDÜR. MariaDB'de düşürülmemesinin
--     tek sebebi "mevcut veriyi korumak"tı, ama canlı veride anket_id'si DOLU 0 satır
--     var (7 sorunun hiçbirinde). Üstelik FK'si ON DELETE CASCADE olduğundan, dolu
--     olsaydı bir anketi silmek soruyu HAVUZDAN silerdi — ara tablonun tam da önlemek
--     için var olduğu şey. Sıfırdan kurulan şemaya bu mayın taşınmaz. Kolon, FK'si,
--     indeksi ve COMMENT'i bu şemada YOKTUR; MariaDB tarafında ise olduğu gibi kalır
--     (orada düşürmek bir UYGULAMA değişikliğidir, bu turun kapsamı değildir).
--   soru_metni          text NN            -> question_text          text NN     (HAM HTML)
--   soru_tipi           varchar(50) NN     -> question_type          varchar(50) NN
--   konu                varchar(255)       -> subject                varchar(255)
--   amac                varchar(255)       -> purpose                varchar(255)
--   sira_no             int                -> sort_order             integer
--   zorunlu_mu          tinyint(1) NN d0   -> is_required            boolean NN d false
--   hazirlayan_kodu     varchar(20) FK     -> prepared_by            bigint FK staff  [TİP: varchar->bigint]
--
-- Secenek -> question_option
--   secenek_id          int PK AI          -> id                     bigint identity PK
--   soru_id             int NN FK          -> question_id            bigint NN FK question
--   secenek_metni       text NN            -> option_text            text NN     (HAM HTML)
--   sira_no             int                -> sort_order             integer
--
-- AnketSoru -> survey_question
--   anket_id            int NN PK1 FK      -> survey_id              bigint NN PK1 FK survey
--   soru_id             int NN PK2 FK      -> question_id            bigint NN PK2 FK question
--   sira_no             int                -> sort_order             integer
--
-- AnketAtama -> survey_assignment
--   atama_id            int PK AI          -> id                     bigint identity PK
--   anket_id            int NN FK          -> survey_id              bigint NN FK survey
--   kullanici_kodu      varchar(20) NN FK  -> staff_id               bigint NN FK staff  [TİP: varchar->bigint]
--   atama_tarihi        datetime NN        -> assigned_at            timestamp NN
--   son_tarih           datetime           -> due_at                 timestamp   (TARİH+SAAT tutar)
--   durum               varchar(20) NN     -> status                 varchar(20) NN
--   baslama_tarihi      datetime           -> started_at             timestamp
--   tamamlanma_tarihi   datetime           -> completed_at           timestamp
--
-- Cevap -> answer
--   cevap_id            int PK AI          -> id                     bigint identity PK
--   atama_id            int NN FK          -> assignment_id          bigint NN FK survey_assignment
--   soru_id             int NN FK          -> question_id            bigint NN FK question
--   secilen_secenek_id  int FK             -> selected_option_id     bigint FK question_option
--   cevap_metni         text               -> answer_text            text        (SERBEST METİN)
--
-- MesajAyrintilari -> survey_message
--   mesaj_id            int PK AI          -> id                     bigint identity PK
--   anket_id            int NN FK          -> survey_id              bigint NN FK survey
--
-- TanimliSecenek -> lookup_value
--   id                  int PK AI          -> id                     bigint identity PK
--   kategori            varchar(50) NN     -> category               varchar(50) NN
--   deger               varchar(100) NN    -> value                  varchar(100) NN
--   UNIQUE(kategori,deger)                 -> UNIQUE(category, value)
--
-- Kısaltmalar: NN = NOT NULL, d = DEFAULT, AI = AUTO_INCREMENT,
--              timestamp = timestamp without time zone.
--
-- ---------------------------------------------------------------------------
-- AD SEÇİMİ HAKKINDA BİR NOT (start_at / end_at / due_at)
-- Host konvansiyonu: "_at" = timestamp (tarih+saat), "_date" = date (yalnız tarih;
-- ör. hire_date, birth_date). Bu üç kolon MariaDB'de datetime idi ve burada
-- timestamp'tir, yani SAAT DE TUTAR; bu yüzden "_at" ile adlandırılmışlardır
-- (start_at / end_at / due_at). Adları tipleriyle örtüşür, ayrık bir istisna yoktur.
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- Tablolar
-- ===========================================================================

-- Anketin kendisi: tanım, yayın durumu, tarih penceresi ve görünürlük ayarları.
CREATE TABLE public.survey (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    intro_text text,
    closing_text text,
    description text,
    status character varying(50) NOT NULL,
    survey_type character varying(50),
    access_level character varying(50),
    -- BLOKE: FK KURULMADI. Karşılığı MariaDB'de KullaniciGrubu(grup_id) idi; host
    -- tarafında grubun hangi tabloya karşılık geleceği ("group" / department / unit /
    -- team) HENÜZ BELİRLENMEMİŞTİR. Kolon bilinçli olarak REFERANSSIZ bırakıldı:
    -- bütünlük şu an DB'de zorlanamaz, hedef netleşince AYRI bir migration ile
    -- FK eklenmelidir. Bu bir unutma değil, bilinen ve kayıtlı bir eksiktir.
    access_group_id bigint,
    start_at timestamp without time zone,
    end_at timestamp without time zone,
    is_mandatory boolean DEFAULT false NOT NULL,
    show_on_home_page boolean DEFAULT false NOT NULL,
    show_question_numbers boolean DEFAULT true NOT NULL,
    question_display_type character varying(50),
    created_by bigint,
    -- LOCALTIMESTAMP (CURRENT_TIMESTAMP değil): kolon "without time zone" olduğundan
    -- CURRENT_TIMESTAMP'in timestamptz sonucu örtük bir dönüşümle yazılırdı. Doğrudan
    -- tz'siz değer üreten LOCALTIMESTAMP kullanılır; MariaDB'deki current_timestamp()
    -- davranışının karşılığıdır.
    created_at timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

-- Soru havuzu. Sorular anketten BAĞIMSIZ tanımlanır; ankete bağlanmaları
-- YALNIZCA survey_question ara tablosu üzerindendir.
-- NOT: MariaDB'deki Soru.anket_id kolonunun burada karşılığı YOKTUR (bilinçli).
-- Migration 011'den beri ölüydü, canlı veride dolu tek satırı yoktu ve CASCADE'li
-- FK'si yüzünden anket silmek soruyu havuzdan silme riski taşıyordu; ayrıntılı
-- gerekçe dosya başındaki kolon eşleme tablosundadır.
CREATE TABLE public.question (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_text text NOT NULL,
    question_type character varying(50) NOT NULL,
    subject character varying(255),
    purpose character varying(255),
    sort_order integer,
    is_required boolean DEFAULT false NOT NULL,
    prepared_by bigint
);

-- Bir sorunun şıkları (çoktan seçmeli / listeden seçmeli / evet-hayır / skala).
CREATE TABLE public.question_option (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id bigint NOT NULL,
    option_text text NOT NULL,
    sort_order integer
);

-- Anket <-> soru bağı (N:M). Bileşik PK, aynı sorunun bir ankete İKİ KEZ
-- eklenmesini DB düzeyinde engeller (MariaDB'deki garanti birebir korunur).
CREATE TABLE public.survey_question (
    survey_id bigint NOT NULL,
    question_id bigint NOT NULL,
    sort_order integer
);

-- Anketin bir PERSONELE atanması ve o kişiye özel ilerleme durumu.
-- status burada KİŞİYE ÖZELDİR ('atandı'/'devam_ediyor'/'tamamlandı') ve anketin
-- kendi yayın durumu olan survey.status ('Aktif'/'Pasif') ile KARIŞTIRILMAZ.
CREATE TABLE public.survey_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    survey_id bigint NOT NULL,
    -- Anket bir KİŞİYE atanır, bir hesaba değil: bu yüzden hedef "user" değil staff.
    -- MariaDB'de varchar(20) sicil kodu idi; host'ta personel kimliği bigint'tir.
    staff_id bigint NOT NULL,
    assigned_at timestamp without time zone NOT NULL,
    due_at timestamp without time zone,
    status character varying(20) NOT NULL,
    started_at timestamp without time zone,
    completed_at timestamp without time zone
);

-- Kullanıcının bir atama kapsamında verdiği tekil cevap. Şık seçimi
-- selected_option_id ile, açık uçlu/yorum cevabı answer_text ile tutulur.
CREATE TABLE public.answer (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assignment_id bigint NOT NULL,
    question_id bigint NOT NULL,
    selected_option_id bigint,
    answer_text text
);

-- Ankete ait mesaj ayrıntıları. MariaDB'de de yalnızca anahtar alanlarıyla
-- duruyordu; içerik alanları netleşince AYRI bir migration ile genişletilir.
CREATE TABLE public.survey_message (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    survey_id bigint NOT NULL
);

-- Yönetilen dropdown sözlüğü (kategori, değer).
-- KAPSAM DARALDI: MariaDB'deki TanimliSecenek 10 kullanıcı-formu dropdown'ını da
-- besliyordu (sirket, birim, bolum, kadro_unvani, gorev_unvani ...). Host'ta kullanıcı
-- yönetimi ZATEN VAR, dolayısıyla o kategoriler bu şemada ÖLÜDÜR. Burada yalnızca
-- sorunun 'konu' ve 'amac' seçenekleri beslenir. Tablo yapısı, ileride başka bir
-- anket sözlüğü gerekirse yeniden kullanılabilsin diye genel bırakılmıştır.
CREATE TABLE public.lookup_value (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category character varying(50) NOT NULL,
    value character varying(100) NOT NULL
);

-- ===========================================================================
-- Birincil anahtarlar
-- ===========================================================================

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT pk_survey PRIMARY KEY (id);

ALTER TABLE ONLY public.question
    ADD CONSTRAINT pk_question PRIMARY KEY (id);

ALTER TABLE ONLY public.question_option
    ADD CONSTRAINT pk_question_option PRIMARY KEY (id);

-- Bileşik PK: (survey_id, question_id) tekilliği aynı zamanda "bir soru bir ankete
-- iki kez eklenemez" iş garantisini DB'de zorlar.
ALTER TABLE ONLY public.survey_question
    ADD CONSTRAINT pk_survey_question PRIMARY KEY (survey_id, question_id);

ALTER TABLE ONLY public.survey_assignment
    ADD CONSTRAINT pk_survey_assignment PRIMARY KEY (id);

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT pk_answer PRIMARY KEY (id);

ALTER TABLE ONLY public.survey_message
    ADD CONSTRAINT pk_survey_message PRIMARY KEY (id);

ALTER TABLE ONLY public.lookup_value
    ADD CONSTRAINT pk_lookup_value PRIMARY KEY (id);

-- ===========================================================================
-- Tekillik kısıtları
-- ===========================================================================

-- Aynı kategoride aynı değer iki kez tanımlanamaz (MariaDB: uq_secenek_kategori_deger).
ALTER TABLE ONLY public.lookup_value
    ADD CONSTRAINT uq_lookup_value_category_value UNIQUE (category, value);

-- ===========================================================================
-- Bütünlük kısıtları (CHECK)
-- MariaDB tarafında bu tablolarda CHECK YOKTU; aşağıdaki tek CHECK bilinçli bir
-- EKLEMEDİR ve raporlanmıştır.
-- ===========================================================================

-- Tamamlanma tutarlılığı: completed_at doluysa durum 'tamamlandı' OLMAK ZORUNDADIR.
-- Uygulama bugün zaten ikisini birlikte yazıyor (cevaplari_kaydet); bu CHECK o
-- garantiyi DB'de de zorlar, böylece yarım kalmış bir yazma tutarsız satır bırakamaz.
-- Ters yön (durum 'tamamlandı' iken completed_at dolu olmalı) BİLEREK zorlanmadı:
-- ileride tarihsiz tamamlama gerekirse şema engel olmasın.
ALTER TABLE ONLY public.survey_assignment
    ADD CONSTRAINT ck_survey_assignment_completion
    CHECK (completed_at IS NULL OR status = 'tamamlandı');

-- ===========================================================================
-- Yabancı anahtarlar — HOST tablolarına (public.staff)
-- staff üretimde host'a aittir; anket modülü ona BAĞLANIR, onu yönetmez.
-- ===========================================================================

-- Anketi oluşturan personel. ON DELETE SET NULL: personel kaydı gitse bile anket
-- KAYBOLMAZ, yalnızca "kim oluşturdu" bilgisi düşer.
ALTER TABLE ONLY public.survey
    ADD CONSTRAINT fk_survey_created_by FOREIGN KEY (created_by)
    REFERENCES public.staff(staff_id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Soruyu hazırlayan personel. Aynı gerekçe: soru havuzu personel silinince boşalmaz.
ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk_question_prepared_by FOREIGN KEY (prepared_by)
    REFERENCES public.staff(staff_id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Anketin atandığı personel. ON DELETE CASCADE (MariaDB ile birebir): personel
-- kaydı silinirse ona ait atama ve -- zincirleme -- cevapları da gider; yetim
-- atama satırı kalmaz.
ALTER TABLE ONLY public.survey_assignment
    ADD CONSTRAINT fk_survey_assignment_staff FOREIGN KEY (staff_id)
    REFERENCES public.staff(staff_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ===========================================================================
-- Yabancı anahtarlar — modül içi
-- Tümü MariaDB'deki ON DELETE/ON UPDATE davranışlarıyla birebirdir.
-- ===========================================================================

-- NOT: MariaDB'deki fk_soru_anket (Soru.anket_id -> Anket) karşılığı YOKTUR; kolonun
-- kendisi taşınmadığı için FK de kurulmaz. Anket-soru bağı survey_question'dadır.

ALTER TABLE ONLY public.question_option
    ADD CONSTRAINT fk_question_option_question FOREIGN KEY (question_id)
    REFERENCES public.question(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.survey_question
    ADD CONSTRAINT fk_survey_question_survey FOREIGN KEY (survey_id)
    REFERENCES public.survey(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.survey_question
    ADD CONSTRAINT fk_survey_question_question FOREIGN KEY (question_id)
    REFERENCES public.question(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.survey_assignment
    ADD CONSTRAINT fk_survey_assignment_survey FOREIGN KEY (survey_id)
    REFERENCES public.survey(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk_answer_assignment FOREIGN KEY (assignment_id)
    REFERENCES public.survey_assignment(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk_answer_question FOREIGN KEY (question_id)
    REFERENCES public.question(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ON DELETE SET NULL (MariaDB ile birebir): şık silinse bile cevap satırı durur,
-- yalnızca hangi şıkkın seçildiği bilgisi düşer.
ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk_answer_selected_option FOREIGN KEY (selected_option_id)
    REFERENCES public.question_option(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.survey_message
    ADD CONSTRAINT fk_survey_message_survey FOREIGN KEY (survey_id)
    REFERENCES public.survey(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ===========================================================================
-- İndeksler
-- PostgreSQL, MariaDB/InnoDB'nin aksine FK kolonlarını KENDİLİĞİNDEN indekslemez.
-- MariaDB'de FK'lerle birlikte oluşan KEY'lerin karşılıkları burada açıkça kurulur.
-- survey_question.survey_id için indeks YOKTUR: bileşik PK'nin ilk kolonu olduğundan
-- PK indeksi zaten onu karşılar (gereksiz ikinci indeks kurulmaz).
-- ===========================================================================

CREATE INDEX ix_survey_access_group_id ON public.survey (access_group_id);
CREATE INDEX ix_survey_created_by ON public.survey (created_by);
CREATE INDEX ix_question_prepared_by ON public.question (prepared_by);
CREATE INDEX ix_question_option_question_id ON public.question_option (question_id);
CREATE INDEX ix_survey_question_question_id ON public.survey_question (question_id);
CREATE INDEX ix_survey_assignment_survey_id ON public.survey_assignment (survey_id);
CREATE INDEX ix_survey_assignment_staff_id ON public.survey_assignment (staff_id);
CREATE INDEX ix_answer_assignment_id ON public.answer (assignment_id);
CREATE INDEX ix_answer_question_id ON public.answer (question_id);
CREATE INDEX ix_answer_selected_option_id ON public.answer (selected_option_id);
CREATE INDEX ix_survey_message_survey_id ON public.survey_message (survey_id);

-- ===========================================================================
-- Kolon açıklamaları (MariaDB COMMENT karşılıkları)
-- ===========================================================================

COMMENT ON COLUMN public.question.question_text IS
    'Biçimlendirilmiş içerik (HTML/markup) tutabilir; düz metin değildir. '
    'Kayıt/gösterim öncesi SUNUCU TARAFINDA sanitizasyon zorunludur (XSS).';

COMMENT ON COLUMN public.question_option.option_text IS
    'Biçimlendirilmiş içerik (HTML/markup) tutabilir; düz metin değildir. '
    'Kayıt/gösterim öncesi SUNUCU TARAFINDA sanitizasyon zorunludur (XSS).';

COMMENT ON COLUMN public.answer.answer_text IS
    'Kullanıcının serbest metin cevabı. Ham kullanıcı girdisidir; yazma ve okuma '
    'sınırında sanitize edilir, sorgulara ASLA birleştirilerek gömülmez (parametre).';

-- ===========================================================================
-- Runtime hesabının yetkileri (en az yetki)
-- savronik_app YALNIZCA veri okur/yazar: DDL (CREATE/ALTER/DROP) VERİLMEZ.
-- NEDEN AYRICA GRANT: 001'deki "GRANT ON ALL TABLES" yalnızca O AN var olan
-- nesneleri kapsar; sonradan gelen bu tablolar oradan yetki DEVRALMAZ. Her migration
-- kendi tablolarını kendisi GRANT'lar.
-- ===========================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON
    public.survey,
    public.question,
    public.question_option,
    public.survey_question,
    public.survey_assignment,
    public.answer,
    public.survey_message,
    public.lookup_value
TO savronik_app;

-- Identity sequence'leri. NOT: identity kolonlarda nextval dahili çağrılır ve
-- PostgreSQL ayrı bir sequence yetkisi ARAMAZ; yine de açıkça verilir ki hesabın
-- yetki yüzeyi tek bakışta okunsun ve ileride serial'a dönen bir kolon INSERT'i
-- sessizce düşürmesin. survey_question'ın identity kolonu yoktur (bileşik PK).
GRANT USAGE, SELECT ON SEQUENCE
    public.survey_id_seq,
    public.question_id_seq,
    public.question_option_id_seq,
    public.survey_assignment_id_seq,
    public.answer_id_seq,
    public.survey_message_id_seq,
    public.lookup_value_id_seq
TO savronik_app;
